//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public int Audit_Log_ID { get; set; }
        public Nullable<System.DateTime> Audit_Log_Date { get; set; }
        public Nullable<System.TimeSpan> Audit_Log_Time { get; set; }
        public string Audit_Log_User { get; set; }
        public string Audit_Log_Transaction_Type { get; set; }
        public string Audit_Log_Critical_Information { get; set; }
    }
}
