//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Order_Line
    {
        public int Sales_ID { get; set; }
        public int Menu_Item_ID { get; set; }
        public string Note { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Menu_Item Menu_Item { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
