//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Write_off_Line
    {
        public int Write_Off_ID { get; set; }
        public int Inventory_Item_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Inventory_Write_Off Inventory_Write_Off { get; set; }
    }
}
