//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Write_Off
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory_Write_Off()
        {
            this.Inventory_Write_off_Line = new HashSet<Inventory_Write_off_Line>();
        }
    
        public int Write_Off_ID { get; set; }
        public string Write_Off_Reason { get; set; }
        public Nullable<System.DateTime> Write_Off_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory_Write_off_Line> Inventory_Write_off_Line { get; set; }
    }
}
