//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Price
    {
        public int Inventory_Price_ID { get; set; }
        public Nullable<int> Inventory_Item_ID { get; set; }
        public Nullable<decimal> Inventory_Price1 { get; set; }
        public Nullable<System.DateTime> Inventory_Price_Date { get; set; }
    
        public virtual Inventory_Item Inventory_Item { get; set; }
    }
}
