//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Item_Price
    {
        public int Menu_Item_Price_ID { get; set; }
        public Nullable<int> Menu_Item_ID { get; set; }
        public Nullable<decimal> Menu_Item_Price1 { get; set; }
        public Nullable<System.DateTime> Menu_Item_Date { get; set; }
    
        public virtual Menu_Item Menu_Item { get; set; }
    }
}
