//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepare_Inventory_Line
    {
        public int Prepare_Inventory_ID { get; set; }
        public int Inventory_Item_ID { get; set; }
        public Nullable<int> Prepare_Inventory_Type_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Prepare_Inventory_Date { get; set; }
        public Nullable<System.TimeSpan> Prepare_Inventory_Time { get; set; }
    
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Prepare_Inventory_Type Prepare_Inventory_Type { get; set; }
    }
}
