//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Line
    {
        public int Sales_ID { get; set; }
        public int Inventory_Item_ID { get; set; }
        public Nullable<int> Sales_Line_Quantity { get; set; }
    
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
