//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public int Employee_ID { get; set; }
        public int Shift_ID { get; set; }
        public Nullable<decimal> Start_Cash { get; set; }
        public Nullable<decimal> End_Cash { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee_Shift Employee_Shift { get; set; }
    }
}
