//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Take_Line
    {
        public int Stock_Take_ID { get; set; }
        public int Inventory_Item_ID { get; set; }
        public Nullable<int> Quantity_Available { get; set; }
        public string Stock_Take_Line_Type { get; set; }
        public Nullable<int> Stock_Take_Line_Type_Quantity { get; set; }
    
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Stock_Take Stock_Take { get; set; }
    }
}
