//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nati_Supermarket_and_Takeaway_WinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Order()
        {
            this.Supplier_Order_List = new HashSet<Supplier_Order_List>();
        }
    
        public int Supplier_Order_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public Nullable<int> Supplier_Payment_Type_ID { get; set; }
        public string Supplier_Order_Status { get; set; }
        public Nullable<decimal> Supplier_Order_Quantity { get; set; }
        public Nullable<System.DateTime> Supplier_Order_Receive_Date { get; set; }
        public Nullable<System.DateTime> Supplier_Payment_Date { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier_Order_List> Supplier_Order_List { get; set; }
        public virtual Supplier_Payment Supplier_Payment { get; set; }
    }
}
